### ISSUE TITLE
Tab Indent Not Getting Picked Up by Prettify

### ISSUE THREAD

**Issue by pjbrow** [adambutler/atom-prettify#3]
I've set my tab length at 4 in the general preferences, and that's working fine.

When I prettify though, the code gets formatted back to 2 space tabs.

Any ideas on fixing this?

**Comment by efc-awebb** [comment]
+1

**Comment by jberube** [comment]
5c1d8bff63b0f6c1d63ac9d144db00e9f7a4d1a8 seems to address this issue, but I think its not yet released.

**Comment by adambutler** [comment]
This has now been shipped
